# name of the action
name: test

# trigger on pull_request or push events
on:
  pull_request:
  push:

# pipeline to execute
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: clone
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: install go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          # use version from go.mod file
          go-version-file: 'go.mod'
          cache: true
          check-latest: true

      - name: test
        run: |
          go test -race -covermode=atomic -coverprofile=coverage.out ./...

      - name: coverage
        uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.out
